spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.data.jdbc.dialect=mysql
spring.servlet.multipart.max-file-size=50
spring.servlet.multipart.max-request-size=50
#spring.sql.init.mode=always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.thymeleaf.cache=false
server.port=3000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=root
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.default_batch_fetch_size=50
jwt.token-issuer=danghieu99
jwt.token-secret-key=monolithEcommerceApplicationSecretKey
jwt.access-token-name=access
jwt.refresh-token-name=refresh
#jwt.access-token-expire-ms=300000
jwt.refresh-token-expire-ms=3600000
jwt.access-token-expire-ms=5000
#springdoc.swagger-ui.path=/swagger-ui.html
minio.endpoint=127.0.0
minio.port=9000
minio.access-key=sIGdvcSa5bNoQzvUCAtl
minio.secret-key=v98zJZWTYg5GdZsg0zrGruvd65eTj167ftLz87tM
minio.bucket-name=product-image
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topics.order.place=place_order
spring.kafka.topics.order.cancel=cancel_order